src.dir=src/main/java
resources.dir=src/main/resources

build.dir=build/ant
classes.dir=${build.dir}/classes
lib.dir=lib

jar.name=Web3Lab.jar
main.class=org.example.Main

test.src.dir=src/test/java
test.classes.dir=${build.dir}/test-classes
test.reports.dir=test-reports

sound.dir=sounds
sound.success=success.wav
sound.fail=error.wav

ssh.host=helios.cs.ifmo.ru
ssh.port=2222
ssh.user=s467922
ssh.remote.path=opi3

svn.repo.url = file:///C:/OPI3/svn-repos/weblab3

env.java.home=C:/Java/corretto-17
#env.java.home=C:/Program Files/Java/jdk-22
env.jvm.args=-Xmx128m -Dfile.encoding=UTF-8

ivy.install.version=2.5.2
ivy.jar.dir=${basedir}/ivy
ivy.jar.file=${basedir}/ivy/ivy.jar

team.dir=team_builds
team.jars.dir=${team.dir}/jars
team.repo.dir=${team.dir}/repo
team.zip.name=revisions_team.zip

git.watch.file=git_watch_list.txt